### ISSUE TITLE
接收到QQ表情时假死

### ISSUE THREAD

**Issue by wyapx** [NatriumLab/python-mirai#15]
在接收到qq表情时（比如斜眼笑）程序会假死 
下面是一些错误信息：
Traceback (most recent call last):
  File "C:\Program Files\Python\Python37\lib\site-packages\mirai\application.py", line 264, in message_polling
    await super().fetchMessage(count)
  File "C:\Program Files\Python\Python37\lib\site-packages\mirai\protocol.py", line 158, in fetchMessage
    result[index]['messageChain'] = MessageChain.custom_parse(result[index]['messageChain'])
  File "C:\Program Files\Python\Python37\lib\site-packages\mirai\event\message\chain.py", line 28, in custom_parse
    return cls(__root__=[ComponentTypes.__members__[m['type']].value.parse_obj(m) for m in value])
  File "C:\Program Files\Python\Python37\lib\site-packages\mirai\event\message\chain.py", line 28, in <listcomp>
    return cls(__root__=[ComponentTypes.__members__[m['type']].value.parse_obj(m) for m in value])
  File "C:\Program Files\Python\Python37\lib\site-packages\pydantic\main.py", line 402, in parse_obj
    return cls(**obj)
TypeError: __init__() got an unexpected keyword argument 'name'
报错以后，程序没有退出，也没有响应

**Comment by Chenwe-i-lin** [comment]
了解 0.2.2将修复.

**Comment by Chenwe-i-lin** [comment]
最近的提交已经修复了该问题, 接下来的 `edge case` 更新会对这种情况做进一步的优化.
