### ISSUE TITLE
ImportError: cannot import name 'session' from 'mirai.network' 

### ISSUE THREAD

**Issue by I-love-study** [NatriumLab/python-mirai#39]
```python
    Traceback (most recent call last):
      File "E:\远程\mirai\python\test.py", line 1, in <module>
        from mirai import Mirai, Image, Plain, MessageChain, Group, Member, Depend
      File "D:\Python38_64\lib\site-packages\mirai\__init__.py", line 9, in <module>
        import mirai.event.message.base
      File "D:\Python38_64\lib\site-packages\mirai\event\message\__init__.py", line 3, in <module>
        from .models import MessageTypes
      File "D:\Python38_64\lib\site-packages\mirai\event\message\models.py", line 4, in <module>
        from mirai.entities.friend import Friend
      File "D:\Python38_64\lib\site-packages\mirai\entities\friend.py", line 4, in <module>
        from mirai.network import session
```
无法导入库，本人现在使用的是python3.8.1,win10 1909，库是从pypi安装的，版本0.2.20

**Comment by Chenwe-i-lin** [comment]
退回0.2.18, 0.2.20居然还没解决...
