### ISSUE TITLE
可发送信息长度

### ISSUE THREAD

**Issue by SukiYume** [NatriumLab/python-mirai#58]
今天遇上了这么件事，发送文本的时候，提示文本过长，然后mirai-console那边也相应报错，发送信息失败。之后python-mirai就跟无头客户端断开连接，无限重联，只能重启。

如果把文本缩减到800字符，依然会报警，不过可以发送了。

想知道mirai最长能发送多长的文本，有没有可能扩展可发送信息长度（不过这看起来像是mirai-console那边的问题，不知道是不是）

如果暂时不能扩展可发送信息长度，是否考虑解决一下无限重连的问题（比如自动约束文本长度，或者重连几次以后放弃该文本发送…）

**python-mirai输出**
```
[2020-04-08 13:27:00][Mirai] WARNING: Protocol: mirai does not support for long string: now its length is 1192
[2020-04-08 13:27:00][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2020-04-08 13:27:05][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
```
**mirai-console输出**
```
21:31:24 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: send message failed
        at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:39)
        at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Chenwe-i-lin** [comment]
经判断, 这不属于 `python-mirai` 的问题, 而是 `mirai-core` 的问题, 请于其他项目处汇报问题.  
顺便.
> **若不是 python-mirai 的问题, 请不要在此处或是用 IM 向我征求解决方法, 先向其他项目汇报问题.**

**Comment by Chenwe-i-lin** [comment]
另: 显然, 发送后 `mirai-console` 处发生了 FATAL 的错误, 以至于 `python-mirai` 无法连接, 现阶段只有重启才能使其恢复正常.

**Comment by Chenwe-i-lin** [comment]
目前就连 `mirai-core` 的开发团队都不能准确的说消息的长度上限, 因此, `python-mirai` 会在消息组件 `Plain` 的实例化过程中判断文本长度是否偏大(阈值为 128), 而实际上, 最新版本的 `mirai-core` 已经支持了群组长消息, 好友长消息有待编写, 就目前看来单纯的 128 长度的 Plain 组件已经可以发出, 所以也请检查整个消息链的大小.

**Comment by SukiYume** [comment]
呀，好吧，多谢。那就只好先分割放送了…

**Comment by Chenwe-i-lin** [comment]
关于无限重连: 在之前的版本中并非无限重连, 但由于一些问题取消了. 而取消消息的发送将会考虑(retry的次数暂定为3次).
