### ISSUE TITLE
sendTempMessage接口异常回显

### ISSUE THREAD

**Issue by Dawnnnnnn** [NatriumLab/python-mirai#61]
示例代码:
```py
async def test():
    await app.sendFriendMessage(friend=110, message='test')
    await app.sendTempMessage(group=220, member=330, message='123')


if __name__ == "__main__":
    sched.add_job(test, 'cron', day_of_week='mon,tue,wed,thu,fri,sat,sun', hour=10, minute=21, second=30)
    sched.start()
    app.run()

```
mirai-console回显:
```java
 10:21:30 [INFO] [NETWORK] Send done: MessageSvc.PbSendMsg
 10:21:30 [INFO] [NETWORK] Event: MessageSvc.PbSendMsg.Response.SUCCESS
 10:21:30 [INFO] [BOT 929644700] QQ(110) <- test
 10:21:30 [INFO] [NETWORK] Send done: MessageSvc.PbSendMsg
 10:21:30 [INFO] [NETWORK] Event: MessageSvc.PbSendMsg.Response.Failed(resultType=102, errorCode=0, errorMessage=发送失败，您与对方不在共同的群，可尝试加对方为好友后聊天)
 10:21:30 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: send message failed
	at net.mamoe.mirai.qqandroid.contact.MemberImpl.sendMessageImpl(MemberImpl.kt:80)
	at net.mamoe.mirai.qqandroid.contact.MemberImpl$sendMessageImpl$1.invokeSuspend(MemberImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
sendFriendMessage 是没有问题的

sendTempMessage报错的信息不是很懂

已确认220的人在330群中，bot也在330群中

不太确定这是http-api的问题还是python sdk的问题

**Comment by Chenwe-i-lin** [comment]
初步判断是 mirai core 的问题, 因为我此前的测试中, 只要有过临时私聊的, sendTempMessage 都成功了(长消息暂时不支持...)

**Comment by Dawnnnnnn** [comment]
刚才看了commit记录里面的test.py，发现是监听了TempMessage事件，然后再用sendTempMessage发送的信息，这个是否是core的限制，只能由对方先建立临时会话联系？我这边是给没建立任何联系的人发的...

**Comment by Chenwe-i-lin** [comment]
我不知道, 你去问 mirai-core 的开发者吧

**Comment by Dawnnnnnn** [comment]
2333，好的

**Comment by Dawnnnnnn** [comment]
已确认，是core的限制。只能先由用户给bot发消息来建立临时会话，bot才可以通过sendTempMessage回复消息。core开发者还在考虑要不要支持主动发起回话，近期应该是用不了这个了
