### ISSUE TITLE
向好友发送本地图片导致console报错

### ISSUE THREAD

**Issue by ssttkkl** [NatriumLab/python-mirai#66]
尝试向好友发送图片时：

```python
@bot.receiver("FriendMessage")
async def test_friend_receiver(bot: Mirai, source: Source, friend: Friend, message: MessageChain):
    if "test" not in message.toString():
        return
    reply_message = [Plain("test"), Image.fromFileSystem("./pixiv_illust/80901007_p0_master1200.jpg")]
    await bot.sendFriendMessage(friend=friend, message=reply_message)
```

mirai-console中日志如下：

```
[0m 11:35:56 [INFO] [NETWORK] Send done: LongConn.OffPicUp[39;49m
[0m 11:35:57 [INFO] [NETWORK] Event: FileExists(resourceId=/1357495247-3595339589-B683CE71ACA45C401025A79AD3E3BA1E, imageInfo=net.mamoe.mirai.qqandroid.network.protocol.data.proto.Cmd0x352$ImgInfo@7ae66a67)[39;49m
[0m 11:36:01 [38;5;196m[ERROR][39;49m [MiraiAPIHTTP] java.lang.IllegalStateException: illegal imageId: //1357495247-3595339589-b683ce71aca45c401025a79ad3e3ba1e. ImageId must matches Regex `/[0-9]*-[0-9]*-[0-9a-zA-Z]{32}`, `/.{8}-(.{4}-){3}.{12}` or `\{.{8}-(.{4}-){3}.{12}}\..*`
        at net.mamoe.mirai.message.data.MessageUtils__ImageKt.calculateImageMd5ByImageId(Image.kt:354)
        at net.mamoe.mirai.message.data.MessageUtils.calculateImageMd5ByImageId(Unknown Source)
        at net.mamoe.mirai.message.data.OfflineFriendImage.<init>(Image.kt:272)
        at net.mamoe.mirai.message.data.MessageUtils__ImageKt.newImage(Image.kt:65)
        at net.mamoe.mirai.message.data.MessageUtils.newImage(Unknown Source)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:186)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:150)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$1$1.invokeSuspend(BaseRoute.kt:351)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$1$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[39;49m
```

mirai-console安装的插件只有MiraiAPIHTTP和ConsoleAddition

**Comment by ssttkkl** [comment]
初步判断为Mirai.handleMessageAsFriend方法中的调用'(await self.handleInternalImageAsFriend(i)).asFriendImage()'的问题。Mirai.handleInternalImageAsFriend方法从MiraiAPIHTTP得到的imageId已经是由'/'开头，而Image.asFriendImage方法又在imageId的开头多添加了一个'/'，导致向MiraiAPIHTTP发送的请求中的imageId不能被正确识别。

**Comment by Chenwe-i-lin** [comment]
已知晓, 将在下个版本中修复

**Comment by Chenwe-i-lin** [comment]
顺便 我希望大家不要直接 `MIrai-Api-HTTP` 这样打出来, 因为这很丑, 直接 `mirai-api-http` 即可
