### ISSUE TITLE
Image类里的fromRemote通过链接发图片不成功

### ISSUE THREAD

**Issue by unhumanplane** [NatriumLab/python-mirai#71]
报错信息如下：
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\application.py", line 395, in executor
    return await self.run_func(executor_protocol.callable, **CallParams, **extra_parameter)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\application.py", line 603, in run_func
    await func(*args, **kwargs)
  File "C:/Users/Administrator/PycharmProjects/qqcollection/main.py", line 39, in event_gm
    await app.sendGroupMessage(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\misc.py", line 125, in wrapper
    raise e
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\misc.py", line 120, in wrapper
    result = await func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\misc.py", line 156, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\protocol.py", line 136, in sendGroupMessage
    "messageChain": await self.handleMessageAsGroup(message),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mirai\protocol.py", line 509, in handleMessageAsGroup
    result.append(json.loads(i.json()))
AttributeError: 'coroutine' object has no attribute 'json'

**Comment by Chenwe-i-lin** [comment]
这是个协程 你要先await
