### ISSUE TITLE
Image.fromFileSystem()发送失败

### ISSUE THREAD

**Issue by Simper16** [NatriumLab/python-mirai#74]
**console ( 0.4.11 )  core ( 0.39.5 ) http ( v1.6.5 )报错**
```
 15:26:14 [INFO] [ConsoleAddition] [NETWORK] Send: ImgStore.GroupPicUp
 15:26:14 [INFO] [ConsoleAddition] [NETWORK] Packet: FileExists(fileId=2729787864, fileInfo=ImgInfo(fileMd
5=[-28, -50, -36, 37, 105, 76, 60, 105, -37, 101, 20, -20, -30, 71, -35, -47], fileType=1000, fileSize=226
8, fileWidth=0, fileHeight=0))
 15:26:14 [ERROR] [MiraiAPIHTTP] java.lang.IllegalArgumentException: illegal imageId: {{E4CEDC25-694C-3C69
-DB65-14ECE247DDD1}.MIRAI}.jpg. ImageId must matches Regex `/.{8}-(.{4}-){3}.{12}`, `/[0-9]*-[0-9]*-[0-9a-
zA-Z]{32}` or `\{.{8}-(.{4}-){3}.{12}\}\.mirai`
        at net.mamoe.mirai.message.data.MessageUtils__ImageKt.newImage(Image.kt:145)
        at net.mamoe.mirai.message.data.MessageUtils.newImage(Unknown Source)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:186)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:150)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVeri
fy$2$1.invokeSuspend(BaseRoute.kt:351)
        at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVeri
fy$2$1.invoke(BaseRoute.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.routing.Routing.executeResult(Routing.kt:147)
        at io.ktor.routing.Routing.interceptor(Routing.kt:34)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
        at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEngi
nePipeline.kt:120)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipel
ine.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
        at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationE
ngine.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**python-mirai ( 0.32 )提示**
```
[2020-04-29 06:32:13][Mirai] INFO: Protocol: protocol method uploadImage was called
[2020-04-29 06:32:14][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2020-04-29 06:32:19][Mirai] INFO: Protocol: protocol method uploadImage was called
[2020-04-29 06:32:19][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
[2020-04-29 06:32:24][Mirai] INFO: Protocol: protocol method uploadImage was called
[2020-04-29 06:32:24][Mirai] ERROR: Protocol: cannot connect to the headless client, will retry after 5 seconds.
```

**Comment by liuzhengyu84** [comment]
同样有这个问题。请问有什么解决方法吗

**Comment by SAGIRI-kawaii** [comment]
同样的问题。。。

**Comment by Chenwe-i-lin** [comment]
正在尽力解决该问题

**Comment by Chenwe-i-lin** [comment]
直接使用 0.3.3 版本以解决问题
