### ISSUE TITLE
运行报错 AttributeError: BotLeaveEventActive

### ISSUE THREAD

**Issue by frencis107** [NatriumLab/python-mirai#77]
运行环境：`Windows 10` `Python 3.7.7`
mirai-console-wrapper 版本：`0.3.0`
mirai-api-http 版本：`v1.6.5`
python-mirai 版本：`v0.3.3`

初次接触这个框架接口，我运行的是文档里的`Hello, world!`示例程序
但使用`python-mirai v0.3.3`的时候会出现以下报错的情况，回退到`v0.3.2`版本是可以正常运行的

错误信息：
```
Traceback (most recent call last):
  File "D:/Bot/bot.py", line 1, in <module>
    from mirai import Mirai, Plain, MessageChain, Friend
  File "D:\Bot\venv\lib\site-packages\mirai\__init__.py", line 37, in <module>
    from mirai.event.external import (
  File "D:\Bot\venv\lib\site-packages\mirai\event\external\__init__.py", line 148, in <module>
    class BotLeaveEventActive(ExternalEvent):
  File "D:\Bot\venv\lib\site-packages\mirai\event\external\__init__.py", line 149, in BotLeaveEventActive
    type: EventType = EventType.BotLeaveEventActive
  File "C:\Program Files\Python37\lib\enum.py", line 349, in __getattr__
    raise AttributeError(name) from None
AttributeError: BotLeaveEventActive

Process finished with exit code 1

```

**Comment by Chenwe-i-lin** [comment]
草。
