### ISSUE TITLE
[问题反馈]ImportError: cannot import name 'AsyncExitStack'

### ISSUE THREAD

**Issue by Atient** [NatriumLab/python-mirai#91]
RT，使用仓库安装，Ubuntu 18.04，Linux version 4.15.0-101-generic，Python 3.6.9，运行了文档中的HelloWorld，报错如下：

Traceback (most recent call last):
  File "mirai_test.py", line 2, in <module>
    from mirai import Mirai, Plain, MessageChain, Friend
  File "/usr/local/lib/python3.6/dist-packages/kuriyama-0.3.6-py3.6.egg/mirai/\_\_init\_\_.py", line 92, in <module>
  File "/usr/local/lib/python3.6/dist-packages/kuriyama-0.3.6-py3.6.egg/mirai/application.py", line 10, in <module>
ImportError: cannot import name 'AsyncExitStack'

查询StackFlow[https://stackoverflow.com/questions/9252543/importerror-cannot-import-name-x]可能是Import twice

以上

**Comment by Chenwe-i-lin** [comment]
请使用 python 3.7 版本, 顺便, 或许你可以从 pypi 处找到 exitstack 的向下迁移版本
